### ISSUE TITLE
Proposal: Implement OpenCollective to accept outside funding contributions from the public

### ISSUE THREAD

**Issue by echel0n** [terra-rebels/tracker#35]
Please see attached file

[Terra Rebels OpenCollective Donation Proposal {PROP #0006}.pdf](https://github.com/terra-rebels/tracker/files/9541412/Terra.Rebels.OpenCollective.Donation.Proposal.PROP.0006.pdf)

**Comment by lokeshs09** [comment]
Related discussions on this topic can be found here:

https://discord.com/channels/978124265482231809/1013493692054651063/1014307991463395380

**Comment by echel0n** [comment]
![image](https://user-images.githubusercontent.com/1128022/187562844-be81689c-63d9-47b1-a02a-ec03233c3fbf.png)

**Comment by echel0n** [comment]
Also, we can become our own Fiscal host as well https://docs.opencollective.com/help/fiscal-hosts/become-a-fiscal-host

**Comment by echel0n** [comment]
![image](https://user-images.githubusercontent.com/1128022/187587272-ff5cbf04-9028-4de7-b3b9-9e4fc5601606.png)
