### ISSUE TITLE
Bug: Unable to run docker/build_all.sh successfully

### ISSUE THREAD

**Issue by shackra** [terra-rebels/tracker#4]
**Describe the bug**
On commit [3430d792408096f6e60edc498c5596f455d23991](https://github.com/terra-rebels/classic-core/commit/3430d792408096f6e60edc498c5596f455d23991) I'm trying to build all Docker images with docker/build_all.sh, however, at some point the script fails with the following:

```
Step 15/16 : EXPOSE 26657
 ---> Using cache
 ---> 4239bccdaedb
Step 16/16 : CMD ["/usr/local/bin/terrad", "version"]
 ---> Using cache
 ---> 4c1a20f386ce
Successfully built 4c1a20f386ce
Successfully tagged terramoney/core:v0.5.11-oracle
Previous HEAD position was 6af0809 Merge branch 'main' into feature/mempool-oracle-priority
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
~/code/rebels.money/classic-core/docker
Sending build context to Docker daemon  15.87kB
Step 1/39 : ARG base_image=terraclassic.terrad-binary
Step 2/39 : ARG version=latest
Step 3/39 : FROM ${base_image}:${version}
pull access denied for terraclassic.terrad-binary, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Sending build context to Docker daemon  15.87kB
Step 1/39 : ARG base_image=terraclassic.terrad-binary
Step 2/39 : ARG version=latest
Step 3/39 : FROM ${base_image}:${version}
pull access denied for terraclassic.terrad-binary, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Sending build context to Docker daemon  15.87kB
Step 1/39 : ARG base_image=terraclassic.terrad-binary
Step 2/39 : ARG version=latest
Step 3/39 : FROM ${base_image}:${version}
pull access denied for terraclassic.terrad-binary, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**To Reproduce**
1. Go to 'docker/'
2. Run `./build_all.sh`
3. See error

**Expected behavior**
The base `terraclassic.terrad-binary` is accessible or built successfully and available to use as base for other docker images.

**System Information(please complete the following information)**
 - OS: Arch Linux
 - Version: None.
 - Docker: Docker version 20.10.17, build 100c70180f
 - Docker Compose: Docker Compose version 2.6.1

**Comment by ZaradarDFDS** [comment]
Its not a bug, if you want this script to work with the new images you need to first build them using the docker-compose v2 toolchain :)

**Comment by shackra** [comment]
>you need to first build them using the docker-compose v2 toolchain :)

I figured that I was required to build the Dockerfile `Dockerfile.terraclassic.terrad-binary`, so I did that with the following command:

```
docker build -t terraclassic.terrad-binary -f Dockerfile.terraclassic.terrad-binary .
```

Now I'll try to run that script again hoping things work this time. I installed the toolchain, I believe:

```
$ docker compose version
Docker Compose version 2.6.1
```

**Comment by shackra** [comment]
same result :(

I'm trying with `make localnet-rebel1-build` to see if this Makefile target does what I expect.
